language: bash

os:
- linux

before_install:
- sudo apt-get update && sudo apt-get install -y shellcheck
script:
- cd /实验四/1-shell
- ls -l
- bash image.sh
- ls -l
- pwd
notifications:
  email:
    on_success: never